name: assignment-04

services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    container_name: pe-dashboard-api
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.backend.rag_search_api:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    container_name: pe-dashboard-ui
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=docker
    command: streamlit run src/frontend/streamlit_app.py
    depends_on:
      - fastapi
